# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170411_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payed', models.BooleanField()),
                ('details', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Category')),
            ],
        ),
    ]
