# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
