# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20170419_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='periodic_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
