# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_periodic_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.PositiveIntegerField(choices=[(0, 'Expense'), (1, 'Income')], default=0),
            preserve_default=False,
        ),
    ]
