# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 00:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170426_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='importance',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
