# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20170525_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='importance',
            new_name='priority',
        ),
    ]
