# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20170704_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodbalance',
            name='account',
        ),
        migrations.DeleteModel(
            name='PeriodBalance',
        ),
    ]
