# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20170815_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='periodic_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.Transaction'),
        ),
    ]
