# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20170910_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='generic_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
