# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transaction_generic_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='periodic_transaction',
            new_name='bound_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bound_reason',
            field=models.CharField(blank=True, choices=[(('PERIODIC',), 'Periodic transaction'), ('ACCOUNT_TRANSFER', 'Transfer between accounts')], max_length=20),
        ),
    ]
