# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20180113_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bound_reason',
            field=models.CharField(blank=True, choices=[('PERIODIC', 'Periodic transaction'), ('ACCOUNT_TRANSFER', 'Transfer between accounts')], max_length=20),
        ),
    ]
