# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20180210_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='current_balance',
            new_name='current_effective_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='current_real_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
