# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20180218_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Active'), (1, 'Archived')], default=0),
        ),
    ]
