# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='start_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
