# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_account_start_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.PositiveIntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'System')]),
        ),
    ]
