# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 22:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_auto_20180916_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
