# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 07:38
from __future__ import unicode_literals

from django.db import migrations

def insert_cpfl(apps, schema_editor):
    Integrations = apps.get_model('integrations', 'Integration')
    db_alias = schema_editor.connection.alias
    Integrations.objects.using(db_alias).create(name_id="cpfl", name="CPFL")

class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_cpfl),
    ]
