# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_InsertCPFL'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchistory',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
