# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_synchistory_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Success'), (1, 'Fail'), (2, 'Partial success')], null=True),
        ),
    ]
