# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20171030_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
