# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0015_auto_20170815_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('closed_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Account')),
            ],
        ),
    ]
