# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodbalance',
            old_name='closed_value',
            new_name='closed_effective_value',
        ),
        migrations.AddField(
            model_name='periodbalance',
            name='closed_real_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
